### ISSUE TITLE
Avoiding clobbering user customizations with Kinto updates

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#480]
This is just something to think about as you move forward with trying to get Kinto packaged and included into distros. I have noticed that when I upgrade to a new version that my `kinto.py` gets replaced by the new one. I can't think off-hand whether the installer script tries to at least back up the `kinto.py` file it's about to overwrite, but overwriting it can end up causing the user to lose all the custom additions or changes they made since they first installed some version of Kinto. For some users it could be years between versions, and they may have made a lot of changes. 

Obviously this is not ideal. 

I wonder if you have a plan already for a way to help the user save their custom lines and integrate them into a new and updated `kinto.py` file as the file continues to evolve with each version. Besides continuing to manually splice back in my "fixes" every time a new Kinto release comes out, like the `xfce4` fix I always had to apply to Linux Mint Cinnamon, I'm not quite sure how to avoid this problem. Especially since a lot of things in `kinto.py` rely on each other and their relationship in the loading order inside the file. 

I have some vague idea about having a few external files that the main `kinto.py` would "inject" or "import" into itself whenever Kinto is (re)started. They would be placed in strategic locations in different sections of the main `kinto.py` file. Like terminals, browsers, GUI apps to override something in the "General GUI" block, and so on. For instance the main file may just contain the "general" mapping blocks while the sub-files would contain mapping blocks dedicated to individual apps, and be automatically inserted into the main file at the right spot when it gets processed. 

Ideally these injection points would be wrapped by a function that checked for syntax errors before loading the external code and would just bypass the whole sub-file without loading it if there was a problem, but continue loading the rest of the `kinto.py` file and successfully start up Kinto, just without that particular set of custom mappings until it gets fixed. And present an informative error message to help the user fix the problem. 

Any of this making any sense? I just feel like as Kinto becomes something that more and more people might have installed through their package manager, and thus possibly updating itself with every system update, there needs to be an easier way for the user to have custom mappings but also take advantage of new optimizations coming from your version of `kinto.py` in each new official release. 

If you just ask during install if the user wants to keep their version of the file (I've seen some software do this when they notice a customized config file) and then don't copy the new one into place, then they never get the benefits of your progress. But if you overwrite their file, they lose whatever they've fixed or changed manually. There must be a Goldilocks approach somewhere in the middle.

**Comment by rbreaves** [comment]
I thought about doing some regex type kung fu, but to be honest.. this problem would likely be better solved by rethinking the overall architecture of the design of the config file itself. I am liking the design of yaml in general and the python config file could be designed to dynamically pull in and build out the python configuration I am willing to bet.

Then there could be a very clear dual yaml file configuration going on. the default.yaml file and a user.yaml file. Both could then be consulted, and merged, with the user.yaml config file taking precedence if there are conflicting remaps btwn the two.

**Comment by rbreaves** [comment]
Proposed future config file layout.

```
# defaults Mac, Win, IBM, Chrome, Winmac
keyboard-type: Mac
app-groups:
  terminals:
    - alacritty
    - deepin-terminal
    - eterm
    - gnome-terminal
    - guake
    - hyper
    - io.elementary.terminal
    - kinto-gui.py
    - kitty
    - konsole
    - lxterminal
    - mate-terminal
    - qterminal
    - sakura
    - terminator
    - tilda
    - tilix
    - xfce4-terminal
    - xterm
  remotes:
    - org.remmina.Remmina
    - xfreerdp
    - VirtualBox Machine
    - VirtualBox
  browsers:
    - Chromium
    - Chromium-browser
    - Discord
    - Epiphany
    - Firefox
    - Google-chrome
    - microsoft-edge
    - microsoft-edge-dev
  chromes:
    - Chromium
    - Chromium-browser
    - Google-chrome
    - microsoft-edge
    - microsoft-edge-dev
multipurpose-modmap:
  Enter2Cmd: false
  Caps2Esc: false
conditional-modmap-gui:
  IBM:
    - Key.LEFT_ALT: Key.RIGHT_CTRL
    - Key.LEFT_CTRL: Key.LEFT_ALT
    - Key.CAPSLOCK: Key.LEFT_META
    - 'Key.RIGHT_ALT: Key.RIGHT_CTRL,  # IBM - Multi-language (Remove)'
    - 'Key.RIGHT_CTRL: Key.RIGHT_ALT,  # IBM - Multi-language (Remove)'
  Chromebook:
  Win:
  Mac:
    - Key.LEFT_META: Key.RIGHT_CTRL  
    - Key.LEFT_CTRL: Key.LEFT_META   
    - 'Key.RIGHT_META: Key.RIGHT_CTRL, # Mac - Multi-language (Remove)'
    - 'Key.RIGHT_CTRL: Key.RIGHT_META, # Mac - Multi-language (Remove)'
conditional-modmap-terminals:
  IBM:
  Chromebook:
  Win:
  Mac:
    - Key.LEFT_META: Key.RIGHT_CTRL
    - 'Key.RIGHT_META: Key.RIGHT_CTRL, # Mac - Multi-language (- move)'
    - 'Key.RIGHT_CTRL: Key.LEFT_CTRL,  # Mac - Multi-language (Remove)'
define-keymaps:
  intellij:
    filter: ^jetbrains-(?!.*toolbox).*$
    remaps:
      - C-Key_0:M-Key_0
      - Super-Grave:C-Grave
  general-gui:
    blacklist: remotes
    remaps:
      - RC-Space:Alt-F1
      - RC-F3:Super-d
    ignore:
      - M-Tab
```

User yaml config can largely be left blank with all possible areas listed for the user to fill in.
```
# defaults Mac, Win, IBM, Chrome, Winmac
keyboard-type: Mac
app-groups:
  terminals:
  remotes:
  browsers:
  chromes:
multipurpose-modmap:
  Enter2Cmd: true
  Caps2Esc: true
conditional-modmap-gui:
  IBM:
  Chromebook:
  Win:
  Mac:
conditional-modmap-terminals:
  IBM:
  Chromebook:
  Win:
  Mac:
define-keymaps:
  intellij:
    filter:
    remaps:
  general-gui:
    blacklist:
    remaps:
    ignore:
```

Although I am not sure about leaving it blank for the user.. because that means if they want to remove something it will be harder, but I also don't want it to clobber the main config after an update by having everything fully defined.. I guess I can have it where they need to provide a - in front of a word or quoted word to see it be excluded, otherwise the main config will use it.
